version: '3.8'

services:
  chatagent-ws:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatagent-ws
    ports:
      - "8001:8001" # Maps host port 8001 to container port 8001
    volumes: []
#      - .:/app # Mounts the local directory to /app in the container
    environment: []
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/docs"] # Healthcheck endpoint
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - chatagent_network

networks:
  chatagent_network:
    external: true  # This tells Docker to use the existing network