[project]
name = "chatagent-ws"
version = "0.1.0"
description = ""
authors = [
    {name = "ggan",email = "yiwugan@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "flask (>=3.1.0,<4.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "gevent (>=24.11.1,<25.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "pydantic (>=2.10.6,<3.0.0)",
    "flask-socketio (>=5.5.1,<6.0.0)",
    "flask-cors (>=5.0.1,<6.0.0)",
    "gunicorn (>=23.0.0,<24.0.0)",
    "gevent-websocket (>=0.10.1,<0.11.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.5"
websocket = "^0.2.1"
websocket-client = "^1.8.0"
gunicorn = "^23.0.0"

